apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Dialogmøtekandiat ved stoppunkt i Oppfolgingstilfelle"
    dcat.data.nav.no/description: >-
      Topic inneholder alle sykemeldte arbeidstakere som har nådd stopppunkt i et Oppfolgingstilfelle for vurdering av dialogmøte og dermed er kandidat for dialogmøte.
  name: isoppfolgingstilfelle-dialogmotekandidat-stoppunkt
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  pool: {{ kafkaPool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykefravr
      application: isoppfolgingstilfelle
      access: readwrite
    - team: teamsykefravr
      application: isdialogmotekandidat
      access: read
