apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Oppfolgingstilfeller for sykmeldte personer"
    dcat.data.nav.no/description: >-
      Topic inneholder full historikk med Oppfolgingstilfeller for sykmeldte personer.
  name: isoppfolgingstilfelle-oppfolgingstilfelle-person
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  pool: {{ kafkaPool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykefravr
      application: isoppfolgingstilfelle
      access: readwrite
    - team: teamsykefravr
      application: isdialogmotekandidat
      access: read
    - team: teamsykefravr
      application: syfooversiktsrv
      access: read
    - team: team-esyfo
      application: syfomotebehov
      access: read
    - team: teamsykefravr
      application: isaktivitetskrav
      access: read
    - team: disykefravar
      application: dvh-sykefravar-airflow-kafka
      access: read
