apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isoppfolgingstilfelle
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isoppfolgingstilfelle.intern.dev.nav.no"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java  
    logging:
      destinations:
        - id: loki
        - id: elastic
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: isoppfolgingstilfelle-db
        diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
        - application: isdialogmotekandidat
        - application: syfomodiaperson
        - application: isbehandlerdialog
        - application: ismeroppfolging
        - application: meroppfolging-backend
          namespace: team-esyfo
        - application: amt-deltaker
          namespace: amt
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
    outbound:
      external:
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "aareg-services-q1.dev-fss-pub.nais.io"
      rules:
        - application: isnarmesteleder
        - application: istilgangskontroll
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  valkey:
    - instance: cache
      access: readwrite
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: KTOR_ENV
      value: "production"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: NARMESTELEDER_URL
      value: "http://isnarmesteleder"
    - name: NARMESTELEDER_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isnarmesteleder"
    - name: ARBEIDSFORHOLD_URL
      value: "https://aareg-services-q1.dev-fss-pub.nais.io"
    - name: ARBEIDSFORHOLD_CLIENT_ID
      value: "dev-fss.arbeidsforhold.aareg-services-nais-q1"
