apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isoppfolgingstilfelle
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 300
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isoppfolgingstilfelle.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: isoppfolgingstilfelle-db
        diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmote
        - application: isdialogmotekandidat
        - application: syfomodiaperson
        - application: isbehandlerdialog
    outbound:
      external:
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "aareg-services.prod-fss-pub.nais.io"
      rules:
        - application: isoppfolgingstilfelle-redis
        - application: isnarmesteleder
        - application: istilgangskontroll
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  tokenx:
    enabled: true
  envFrom:
    - secret: isoppfolgingstilfelle-redis-password
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: REDIS_HOST
      value: "isoppfolgingstilfelle-redis.teamsykefravr.svc.cluster.local"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: NARMESTELEDER_URL
      value: "http://isnarmesteleder"
    - name: NARMESTELEDER_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isnarmesteleder"
    - name: ARBEIDSFORHOLD_URL
      value: "https://aareg-services.prod-fss-pub.nais.io"
    - name: ARBEIDSFORHOLD_CLIENT_ID
      value: "prod-fss.arbeidsforhold.aareg-services-nais"
