apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isoppfolgingstilfelle
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 600m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 384Mi
  ingresses:
    - "https://isoppfolgingstilfelle.dev.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: isoppfolgingstilfelle-db
        diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-dev
  env:
    - name: KTOR_ENV
      value: "production"
    - name: TOGGLE_KAFKA_SYKETILFELLEBIT_PROCESSING_ENABLED
      value: "false"
