ALTER TABLE TILFELLE_BIT
ADD COLUMN ready BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN processed BOOLEAN NOT NULL DEFAULT TRUE;

CREATE INDEX IX_TILFELLE_BIT_NOT_READY
ON TILFELLE_BIT(id)
WHERE NOT ready;

CREATE INDEX IX_TILFELLE_BIT_NOT_PROCESSED
ON TILFELLE_BIT(id)
WHERE ready AND NOT processed;
