ALTER TABLE TILFELLE_BIT
ADD COLUMN IF NOT EXISTS to_be_deleted BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS IX_TILFELLE_BIT_TO_BE_DELETED
ON TILFELLE_BIT(id)
WHERE to_be_deleted AND processed;
