name: kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/kafka-dialogmotekandidat-stoppunkt.yaml'
      - '.nais/kafka/dialogmotekandidat-stoppunkt.yaml'
      - '.nais/kafka/dev.json'
      - '.nais/kafka/prod.json'

jobs:
  deploy-kafka-dialogmotekandidat-dev:
    name: Deploy Kafka topic Dialogmotekandidat to NAIS dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/dialogmotekandidat-stoppunkt.yaml
          VARS: .nais/kafka/dev.json

  deploy-kafka-dialogmotekandidat-prod:
    name: Deploy Kafka topic Dialogmotekandidat to NAIS prod-gcp
    needs: deploy-kafka-dialogmotekandidat-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/dialogmotekandidat-stoppunkt.yaml
          VARS: .nais/kafka/prod.json

